### PR TITLE
Support for GitHub link

### PR DESCRIPTION
**Pull request by daniele-athome**
This pull features a GitHub link with the octopus mark. It's my first time editing a TeX class I hope I did everything right :-)

Signed-off-by: Daniele Ricci <daniele.athome@gmail.com>

### CODE REVIEW

**Comment by daniele-athome** [comment]
Oh, I just saw #16...

**Comment by lnicola** [comment]
I think @leinardi mentioned he's not getting the GitHub notifications for this repository, so PRs stay open a long time.

**Comment by daniele-athome** [comment]
Thank you @lnicola, I'll just keep it open and continue on my own fork then.

**Comment by leinardi** [comment]
Hey guys, yep I don't get notifications for new PR but I get them for mentions :)

The PR looks good to me. I'll merge it.

**Comment by daniele-athome** [comment]
Thank you!

**Pull request merged**
